name: Unit testing with pytest
on: [push] # when should we run this action
  paths:
      - 'unit.py'
jobs:
  -test: 
  build:
    runs-on: ubuntu-latest # platform it runs on
    steps:
    - uses: actions/checkout@v2 # checkout your code
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # specify python version
    - name: Install dependencies # which libraries do we need for testing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # they should be listed in this file
    - name: Test with pytest
      run: |
        pip install pytest
        pytest unit.py
